### ISSUE TITLE
Lichess module integration

### ISSUE THREAD

**Issue by joaomrcarvalho** [Alistair-Crompton/DGTCentaurMods#1]
The Lichess module is currently broken, as it still isn't integrated with the new code.

**Comment by Alistair-Crompton** [comment]
The legacy Lichess module does not use anything from the new code.
What do you mean by broken? Could you provide details about that?

**Comment by djaramil** [comment]
I think we just need to go through it and identify what needs to udpated.
One item is that we need a menu on the Web UI to be able to put the API key in there.  
The previous code had that option.

**Comment by Alistair-Crompton** [comment]
A new Lichess alpha module has been implemented.
You can edit your Lichess token using the web interface (system>edit configuration file)

The module is quite simple but fully playable.
Sofar, no direct challenge creation or acceptance from the Centaur.

In order to play, you need to first launch the module, then create a game from the Lichess web interface, using your laptop or your phone.

If an issue occurs, you can resume a running game by relaunching the Lichess module, the module will catch-up the moves then you will be able to continue your game.
